### ISSUE TITLE
SSO jump does not work

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-demo-ehr#17]
SSO jump requires the user's name in the access token, which is obtained using the IRMA flow. Default the v1 contract is used which retrieves the AGB-code but doesn't include the person's name. The v2 contract does include the name, but doesn't include the AGB-code which is required for the zorginzage use case.

**Comment by reinkrul** [comment]
@stevenvegt @Timendus

**Comment by stevenvegt** [comment]
We can use the v2 contract for the use case `zorginzage` and use the agb from the new access token instead of the one from the v1 contract.

**Comment by woutslakhorst** [comment]
obsolete
