### ISSUE TITLE
Revocation of NutsAuthCreds is done too quickly

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-demo-ehr#272]
A handoff is marked as complete at the receiver. It updates the Task at the sender. The sender immediately revokes the NutsAuthCred AND sends a Task notification. The task can no longer be retrieved because of the revoked credential.

Maybe for demo purposes don't revoke any credential?

**Comment by reinkrul** [comment]
Or revoke after an hour or so? As in, best-effort? (it might not revoke in all cases, e.g. restart, but it still shows what should be done, in code)
