### ISSUE TITLE
Update Task is not compatible with .net fhir libary

### ISSUE THREAD

**Issue by HvanderGeest** [nuts-foundation/nuts-demo-ehr#294]
The current implementation of the update Task breaks when called from the fhir client from the .net fhir library(Hl7.Fhir.STU3). The suspected reason for this is that it tries to parse the response to a fhir resource and at the moment the update Task doesn't return [any body](https://github.com/nuts-foundation/nuts-demo-ehr/blob/2cae8af11cde2271d899f92f112ce658ac99fc55/api/internal.go#L43). Preferably the update task endpoint returns the Task that was updated.

**Comment by reinkrul** [comment]
Task update method is not according to spec, according to https://www.hl7.org/fhir/stu3/http.html#update :
> A server SHOULD accept the resource as submitted when it accepts the update, and return the same content when it is subsequently read. However systems may not be able to do this; see the note on [transactional integrity](https://www.hl7.org/fhir/stu3/http.html#transactional-integrity) for discussion. Also, see [Variations between Submitted data and Retrieved data](https://www.hl7.org/fhir/stu3/updates.html) for additional discussion around update behavior. Note that update generally updates the whole content of the resource. For partial updates, see [patch](https://www.hl7.org/fhir/stu3/http.html#patch) below.
