### ISSUE TITLE
FHIR proxy should enforce/filter by requesting organizations when listing Tasks

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-demo-ehr#79]
The receiving care organization queries `/Task`, but neither the FHIR server or FHIR server proxy filter/enforce whether the organization is actually allowed to see all of the returned tasks (currently filtering is done client-side at domain/inbox/service.go:107)

**Comment by dmeijboom** [comment]
Closing for now. We're going to discuss other possible implementations (such as notifications based on task ID where the task search endpoint isn't being used at all).
